### ISSUE TITLE
Error Running LARA Script - "Module not found: '@specs-feup/lara/api/lara/Io.js'"

### ISSUE THREAD

**Issue by ManelMCCS** [specs-feup/lara-framework#78]
When running a LARA script, an error occurs related to the lack of a JavaScript module, resulting in the following exception:

```
Exception in thread "main" java.lang.RuntimeException: Exception while executing LARA script
at larai.LaraI.execPrivate(LaraI.java:457)
at larai.LaraI.lambda$exec$3(LaraI.java:325)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1583) Caused by: ception: Exception during interpretation at larai.LaraI.execPrivate(LaraI.java:267) at larai.LaraI.execPrivate(LaraI.java:442) ... 5 more Caused by: java.lang.RuntimeException: Polyglot exception while evaluating JavaScript code at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine.eval(GraalvmJsEngine.java:279) at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine.eval(GraalvmJsEngine.java:194) at pt.up.fe.specs.jsengine.graal.GraalvmJsEngine. evalFile(GraalvmJsEngine.java:296) at pt.up.fe.specs.jsengine.JsEngine.evalFile(JsEngine.java:286) at pt.up.fe.specs.jsengine.JsEngine.evalFile(JsEngine.java:282) at org.lara.interpreter.Interpreter.evaluate(Interpreter.java:247) at org.lara.interpreter.Interpreter.executeMainAspect(Interpreter.java:158) at larai.LaraI.interpret(LaraI.java:756) at larai.LaraI.execPrivate(LaraI.java:254) ... 6 more Caused by: org.graalvm.po lyglot.PolyglotException: TypeError: Module not found: '@specs-feup/lara/api/lara/Io.js' at org.graalvm.polyglot.Context.eval(Context.java:399) at en.up.fe.specs.jsengine.graal.GraalvmJsEngine.eval(GraalvmJsEngine.java:239)
... 14 more
```

**Additional Details:**
- The error may be related to the path of the `node_modules` modules.

**Steps to Reproduce:**
1. Run a LARA script that uses the `@specs-feup/lara/api/lara/Io.js` module.
2. Note the failure when trying to locate the JavaScript module.

**Temporary Workaround:**
Moving the `node_modules` folder from the `/tmp` directory to the correct directory seems to resolve the issue.

**Comment by joaobispo** [comment]
In what conditions does this error happens (e.g., operating system, running of docker, etc)?

It is mentioned that "moving the `node_modules` folder from the `/tmp` directory to the correct directory seems to resolve the issue". What is the correct directory?

**Comment by joaobispo** [comment]
This [commit](https://github.com/specs-feup/lara-framework/commit/ac5fea6483e50fef9145e9a105f55bad5c7d50e4) closes this issue.
